In [1]:
import json
import pandas as pd
import numpy as np
from pandas.io.json import json_normalize

# Pandas by default limit the maximum columns display. This will remove the limit.
pd.set_option('display.max_columns', None)

tweets = []
df = pd.DataFrame()

In [2]:
twitter_filename = "2017-09-22:03:05:01.json"
twitter_file = open(twitter_filename, 'r')

In [14]:
selected_columns = ['id_str',
                    'created_at', 
                    'text', 
                    'entities.hashtags', 
                    'lang',
                    'user.screen_name', 
                    'user.id_str',
                    'user.followers_count',
                    'user.friends_count',
                    'retweeted_status.id_str',
                    'retweeted_status.created_at',
                    'retweeted_status.text',
                    'retweeted_status.entities.hashtags',
                    'retweeted_status.lang',
                    'retweeted_status.user.screen_name',
                    'retweeted_status.user.id_str',
                    'retweeted_status.user.followers_count',
                    'retweeted_status.user.friends_count']

In [15]:
df_tweets = pd.DataFrame()
with open(twitter_filename, 'r') as f:
    for line in f:
        tweet = json.loads(line)
        df = json_normalize(tweet)
        df_tweets = df_tweets.append(df.loc[:,selected_columns], ignore_index=True)

In [16]:
df_tweets.head()

,id_str,created_at,text,entities.hashtags,lang,user.screen_name,user.id_str,user.followers_count,user.friends_count,retweeted_status.id_str,retweeted_status.created_at,retweeted_status.text,retweeted_status.entities.hashtags,retweeted_status.lang,retweeted_status.user.screen_name,retweeted_status.user.id_str,retweeted_status.user.followers_count,retweeted_status.user.friends_count
0,911048657474113536,Fri Sep 22 02:05:01 +0000 2017,EuropeUnion : Click HERE▶️https://t.co/iwDoMV6...,"[{u'indices': [50, 53], u'text': u'EU'}, {u'in...",fr,nathymora,308046422,611,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,911048676205826048,Fri Sep 22 02:05:05 +0000 2017,Click HERE▶️https://t.co/Y3loSofx8E\n#EU #News...,"[{u'indices': [36, 39], u'text': u'EU'}, {u'in...",en,EuropeUnion,194119186,9489,586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,911048690529431552,Fri Sep 22 02:05:08 +0000 2017,EuropeUnion : Click HERE▶️https://t.co/hWrKk2Z...,"[{u'indices': [50, 53], u'text': u'EU'}, {u'in...",en,nathymora,308046422,611,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,911048692567760896,Fri Sep 22 02:05:09 +0000 2017,RT @tsemtulku: Three art styles to see! https:...,"[{u'indices': [65, 74], u'text': u'buddhism'},...",en,KumarTa69783205,882043107776184320,18,56,909939266695790592,Tue Sep 19 00:36:41 +0000 2017,Three art styles to see! https://t.co/sD090hDa...,"[{u'indices': [50, 59], u'text': u'buddhism'},...",en,tsemtulku,23065876,452447.0,169.0
4,911048712570462210,Fri Sep 22 02:05:14 +0000 2017,Thread. #Brexit https://t.co/oG4MqhTJMt,"[{u'indices': [8, 15], u'text': u'Brexit'}]",en,SergioTavaresUK,2178018878,203,418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_tweets.tail()

,id_str,created_at,text,entities.hashtags,lang,user.screen_name,user.id_str,user.followers_count,user.friends_count,retweeted_status.id_str,retweeted_status.created_at,retweeted_status.text,retweeted_status.entities.hashtags,retweeted_status.lang,retweeted_status.user.screen_name,retweeted_status.user.id_str,retweeted_status.user.followers_count,retweeted_status.user.friends_count
743,911063638483591168,Fri Sep 22 03:04:32 +0000 2017,RT @eerickarchila: follow me - Catalan leader ...,"[{u'indices': [108, 118], u'text': u'Catalonia...",en,harry1911foot,893465262737043456,2,13,911048042727407616,Fri Sep 22 02:02:34 +0000 2017,follow me - Catalan leader accuses Spain of vi...,"[{u'indices': [89, 99], u'text': u'Catalonia'}...",en,eerickarchila,813458364206235648,426.0,1119.0
744,911063643378339840,Fri Sep 22 03:04:33 +0000 2017,RT @champagne_lefty: Those who question #Brexi...,"[{u'indices': [40, 47], u'text': u'Brexit'}]",en,sound_of_sirens,128929917,305,181,910842653465382912,Thu Sep 21 12:26:25 +0000 2017,Those who question #Brexit are unbelievers and...,"[{u'indices': [19, 26], u'text': u'Brexit'}]",en,champagne_lefty,3310749201,4269.0,4968.0
745,911063663469105152,Fri Sep 22 03:04:38 +0000 2017,"Every person deserves to be safe, happy, healt...","[{u'indices': [60, 76], u'text': u'RefugeesWel...",en,anupreet79,1157802895,18,70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746,911063731379097603,Fri Sep 22 03:04:54 +0000 2017,RT @eerickarchila: follow me - Catalan leader ...,"[{u'indices': [108, 118], u'text': u'Catalonia...",en,CatalanRobot,905779194088579072,142,1,911048042727407616,Fri Sep 22 02:02:34 +0000 2017,follow me - Catalan leader accuses Spain of vi...,"[{u'indices': [89, 99], u'text': u'Catalonia'}...",en,eerickarchila,813458364206235648,426.0,1119.0
747,911063731580182532,Fri Sep 22 03:04:55 +0000 2017,Michael Heseltine: #Brexit won't happen and we...,"[{u'indices': [19, 26], u'text': u'Brexit'}]",en,JumMurphy,3019712643,5997,4743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
def convert_hashtags(entries):
    hashtags = []
#     print (entries)
    if (entries != "NO HASHTAGS"): 
        if (len(entries) == 0):
            return "NO HASHTAGS"
        else:
            for entry in entries: # for each line in our input
    #             print(entry['text'])
    #             for ht in entry: # for every hashtag in each line
    #                 print (ht)
                hashtags.append(entry['text'])
            return hashtags
    else:
        return "NO HASHTAGS"

In [28]:
df_tweets['entities.hashtags'] = df_tweets['entities.hashtags'].astype('object').fillna("No Hashtags")
df_tweets['retweeted_status.entities.hashtags'] = df_tweets['retweeted_status.entities.hashtags'].astype('object').fillna("NO HASHTAGS")

In [29]:
df_tweets['retweeted_status.entities.hashtags'] = df_tweets['retweeted_status.entities.hashtags'].apply(lambda row: convert_hashtags(row))
df_tweets['entities.hashtags'] = df_tweets['entities.hashtags'].apply(lambda row: convert_hashtags(row))

In [31]:
#df_tweets.to_csv('Export.csv')

In [5]:
#df_tweets = pd.read_csv('Export.csv', index_col = 0)

In [32]:
df_tweets.tail()

,id_str,created_at,text,entities.hashtags,lang,user.screen_name,user.id_str,user.followers_count,user.friends_count,retweeted_status.id_str,retweeted_status.created_at,retweeted_status.text,retweeted_status.entities.hashtags,retweeted_status.lang,retweeted_status.user.screen_name,retweeted_status.user.id_str,retweeted_status.user.followers_count,retweeted_status.user.friends_count
743,911063638483591168,Fri Sep 22 03:04:32 +0000 2017,RT @eerickarchila: follow me - Catalan leader ...,"[Catalonia, Spain, Europe]",en,harry1911foot,893465262737043456,2,13,911048042727407616,Fri Sep 22 02:02:34 +0000 2017,follow me - Catalan leader accuses Spain of vi...,"[Catalonia, Spain, Europe]",en,eerickarchila,813458364206235648,426.0,1119.0
744,911063643378339840,Fri Sep 22 03:04:33 +0000 2017,RT @champagne_lefty: Those who question #Brexi...,[Brexit],en,sound_of_sirens,128929917,305,181,910842653465382912,Thu Sep 21 12:26:25 +0000 2017,Those who question #Brexit are unbelievers and...,[Brexit],en,champagne_lefty,3310749201,4269.0,4968.0
745,911063663469105152,Fri Sep 22 03:04:38 +0000 2017,"Every person deserves to be safe, happy, healt...","[RefugeesWelcome, 1DayWithoutUs]",en,anupreet79,1157802895,18,70,NaN,NaN,NaN,NO HASHTAGS,NaN,NaN,NaN,NaN,NaN
746,911063731379097603,Fri Sep 22 03:04:54 +0000 2017,RT @eerickarchila: follow me - Catalan leader ...,"[Catalonia, Spain, Europe]",en,CatalanRobot,905779194088579072,142,1,911048042727407616,Fri Sep 22 02:02:34 +0000 2017,follow me - Catalan leader accuses Spain of vi...,"[Catalonia, Spain, Europe]",en,eerickarchila,813458364206235648,426.0,1119.0
747,911063731580182532,Fri Sep 22 03:04:55 +0000 2017,Michael Heseltine: #Brexit won't happen and we...,[Brexit],en,JumMurphy,3019712643,5997,4743,NaN,NaN,NaN,NO HASHTAGS,NaN,NaN,NaN,NaN,NaN